providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd backend && pip install -r requirements.txt[aws,azure,gcp]"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port 8000"
