providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd backend && pip install -r requirements.txt[aws,azure,gcp]"
]

[start]
cmd = "bash start.sh"
