services:
  - type: web
    name: elch-backend
    env: python
    plan: free  # Use 'free' for free tier
    region: oregon  # Specify region for better performance
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements-render.txt
      python -c "import sys; print(f'Python version: {sys.version}')"
    startCommand: |
      python -c "from core.db import init_db; init_db()" || true
      gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:$PORT --timeout 300 --keep-alive 5 --max-requests 100 --preload --log-level info --access-logfile - --error-logfile -
    healthCheckPath: /healthz
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: RELOAD
        value: false
      - key: WORKERS
        value: 4
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SESSION_SECRET
        generateValue: true  # Render will generate a secure secret
      - key: FERNET_KEY
        generateValue: true  # Render will generate a secure key
      - key: CIRCUIT_BREAKER_FAILURE_THRESHOLD
        value: 5
      - key: CIRCUIT_BREAKER_RECOVERY_TIMEOUT
        value: 60
      - key: MAX_RETRIES
        value: 3
      - key: RATE_LIMIT_PER_MINUTE
        value: 60
      - key: LOG_LEVEL
        value: INFO
      - key: ENABLE_PERFORMANCE_MONITORING
        value: true
      - key: ENABLE_SELF_LEARNING
        value: true
      - key: ENABLE_LOCAL_EMBEDDINGS
        value: false  # Disable for free tier to reduce memory usage
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
      # Required environment variables - set these in Render dashboard:
      # - DATABASE_URL (from PostgreSQL addon)
      # - GEMINI_API_KEYS (your Gemini API keys, comma-separated)
      # - GOOGLE_CLIENT_ID (optional, for OAuth)
      # - GOOGLE_CLIENT_SECRET (optional, for OAuth)
      # - OPENAI_API_KEY (optional, for OpenAI integration)

databases:
  - name: elch-postgres
    plan: free  # Use free tier
    databaseName: elch_db
    user: elch_user