name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Nixpacks
        uses: railwayapp/nixpacks-action@v1

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/multi-cloud-agent:latest .
